version: "3"

services:
  pet-db:
    image: "postgres"
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret1234!
    volumes:
      - "./petstoredb:/docker-entrypoint-initdb.d/init.sql"

  pet-api:
    image: "jurosm/pet-store-api"
    container_name: pet-api
    ports:
      - 5001:80
    environment:
      - DB_CONNECTION_STRING=User ID=postgres;Password=secret1234!;Server=pet-db;Port=5432;Database=postgres;
      - AUTH0_DOMAIN=
      - AUTH0_AUDIENCE=
      - AUTH0_CLIENT_ID=
      - AUTH0_CLIENT_SECRET=
      - STRIPE_SECRET=
    depends_on:
      - pet-db

  pet-ui:
    image: "jurosm/pet-store"
    container_name: pet-app
    ports:
      - 4200:4200
    depends_on:
      - pet-api
    environment:
      - API_URL=http://localhost:5001/
