export DB_CONNECTION_STRING="User ID=postgres;Password=secret1234!;Server=localhost;Port=5432;Database=postgres;"
export AUTH0_DOMAIN="codespace.eu.auth0.com"
export AUTH0_AUDIENCE="https://api.code-space.dev"
export AUTH0_CLIENT_ID="5H9DACmtMh0zMZWYZD7DKKLKAJZwzrwd"
export AUTH0_CLIENT_SECRET="p-c-kRIiZYDdZlVvp1W7oy11doJLqGwNUkTFnJy3wNqNPJUhtxIWBxCnXxobheDc"
export STRIPE_SECRET="sk_test_51G4PgkLOGOt5JdU3KIQSbAP45W8VRk91PG5bEgbiE5VvANazFhtwlOAqOwbTieI851H4EtViT8Wt5LA0TJVEA57000gesgotQE"